### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by tnilzon** [mhogomchungu/media-downloader#395]
Not able to update anymore. Media Downloader does not update, svtplay-dl does not update. As for Media Downloader, it indicates "Update Complete, Restart To Use New Version", but when restarting, the update process starts all over.

OS Name	Microsoft Windows 11 Pro, Version 10.0.22631 Build 22631
Media Downloader Version: 4.4.0.132001/4.5.0
Media Downloader Log file is attached.

[error_messages.txt](https://github.com/mhogomchungu/media-downloader/files/15126516/error_messages.txt)

**Comment by mhogomchungu** [comment]
Steps to take to correct the problem:-
1. Close Media Downloader.
2. Delete folder at "C:/Users/tomas/AppData/Roaming/media-downloader/update".
3. Manually update Media Downloader using a git installer located at below path.

Known bug and is already fixed. Older git versions before a certain version have to manually be updated to jump over this endless loop.

The problem is caused by presence of both "MediaDownloader-4.5.0.zip" and "MediaDownloader.git.zip" files. The git version you are using wrongly picks the first one above because github lists its first. 

The bug started showing up after i added "MediaDownloader-4.5.0.zip" file and a solution here is either for me to remove it and not put released version here or for users to manually update their old git versions they are using and i decided to go with the latter solution.

https://github.com/mhogomchungu/media-downloader-git/releases/download/0.0.0/MediaDownloader.git.setup.exe

**Comment by tnilzon** [comment]
Thanks, that fixed the problem with Media Downloader, but the problem with svtplay-dl not being updated still persists.
[error_messages.txt](https://github.com/mhogomchungu/media-downloader/files/15128207/error_messages.txt)

**Comment by mhogomchungu** [comment]
1. Close Media Downloader.
2. Delete folder "C:/Users/tomas/AppData/Roaming/media-downloader/bin/svtplay-dl"
3. Start Media Downloader and check it continues to fail to update.

**Comment by tnilzon** [comment]
That worked, many thanks!
[update_messages.txt](https://github.com/mhogomchungu/media-downloader/files/15128616/update_messages.txt)

**Comment by mhogomchungu** [comment]
Glad it worked.

That folder is supposed to be deleted before extraction start and will investigate why it was not happening in your case.

**Comment by tnilzon** [comment]
Great, thanks.RegardsTomas<Sent from my Galaxy>
-------- Original message --------From: mhogomchungu ***@***.***> Date: 4/26/24  12:12  (GMT+01:00) To: mhogomchungu/media-downloader ***@***.***> Cc: Tomas NIlzon ***@***.***>, Author ***@***.***> Subject: Re: [mhogomchungu/media-downloader] Unable to update (Issue #395) 
Glad it worked.
That folder is supposed to be deleted before extraction start and will investigate why it was not happening in your case.
